language: node_js
sudo: false
node_js:
- node

install:
  - npm install

script:
  - npm run build
  - npm run coverage

after_success:
  - npm run coverage:send:coveralls

cache:
  directories:
  - node_modules